### PR TITLE
Rename Pattern to Pattern.py

### PR DESCRIPTION
**Pull request by ayu2606**
This will make your repo no sus to github

### CODE REVIEW

**Comment by ayu2606** [comment]
> ok!! btw i am really sorry, i don't remember ayush kon tha, ek baar bata do . i am bad at remembering names :)

aare mai toh ek github user hu, same interest hai tumara toh socha ki help krdu

**Comment by ayu2606** [comment]
btw check my site https://ayush.codes , also if you want then we can work on some projects together

**Comment by garimagupta2009** [comment]
ok! sure i will reach out to you

**Comment by CR072** [comment]
Dammit, @garimagupta2009 He's like a virus, a random predator from the Internet. By the way, don't tell my real name to anyone.

**Comment by CR072** [comment]
Shouldn't have followed you with this account.

**Comment by CR072** [comment]
> You can tell me his real name, i am his friend.

Sir, respectfully, now who are you and where did you come from?

**Comment by ayu2606** [comment]
respectfully @garimagupta2009 , i have proof of cr072 stalking you, and even he stalks your classmates, he is a stalker, don't listen to him, and yeah I'm not a predator, I fork random repos

**Comment by ayu2606** [comment]
> > You can tell me his real name, i am his friend.
> 
> Sir, respectfully, now who are you and where did you come from?

he's demon bro

**Comment by CR072** [comment]
Well, I think we should keep our business out of here.

**Comment by ayu2606** [comment]
image
also he is weirdo

**Comment by ayu2606** [comment]
> Well, I think we should keep our business out of here.

sure, you only started it anyways

**Comment by CR072** [comment]
Now clean up this mess from here

**Comment by ayu2606** [comment]
> > > Well, I think we should keep our business out of here.
> > 
> > 
> > sure, you only started it anyways
> 
> Cause of your madness.

you are just mad coz garima is your crush and nothing else

**Comment by ayu2606** [comment]
> Now clean up this mess from here

sure

**Comment by ayu2606** [comment]
> Dude, the only think I did was follow her with this fucking account. I did nothing else.

yeah u didn't, but she is ur crush u accepted it bro, don't lie, I cant share ss coz of LOC of the gc

**Comment by CR072** [comment]
LOC? Where did that come from? Didn't you already break it when you sent another screenshot? And... think about what will happen to you if I leak all your chats? Bet you'd be jailed for your entire life.

**Comment by CR072** [comment]
> > LOC? Where did that come from? Didn't you already break it when you sent another screenshot? And... think about what will happen to you if I leak all your chats? Bet you'd be jailed for your entire life.
> 
> same bro, u too, you stalk girls

Stalking girls is not my in Code of conduct. I only stalk criminals like you.

**Comment by ayu2606** [comment]
> > > LOC? Where did that come from? Didn't you already break it when you sent another screenshot? And... think about what will happen to you if I leak all your chats? Bet you'd be jailed for your entire life.
> > 
> > 
> > same bro, u too, you stalk girls
> 
> Stalking girls is not my in Code of conduct. I only stalk criminals like you.

khaa maa kasam

**Comment by ayu2606** [comment]
well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere

**Comment by CR072** [comment]
> well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere

When the hell did I do that?

**Comment by CR072** [comment]
Well, my lawyer will contact you, shortly.

**Comment by ayu2606** [comment]
> > well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere
> 
> When the hell did I do that?

ask me what you didn't did in terms of stalking girls and making deep fake

**Comment by ayu2606** [comment]
> Well, my lawyer will contact you, shortly.

yeah sure my email is ayush@ayush.codes

**Comment by CR072** [comment]
You already broke [GitHub's guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).

**Comment by ayu2606** [comment]
> You already broke [GitHub's guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).

how?

**Comment by CR072** [comment]
> > > well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere
> > 
> > 
> > When the hell did I do that?
> 
> ask me what you didn't did in terms of stalking girls and making deep fake

What kind of question is that? You're the one who sent porn in that group chat.

**Comment by CR072** [comment]
> > You already broke [GitHub's guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).
> 
> how?

Read it you fricking illiterate.

**Comment by ayu2606** [comment]
> > > > well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere
> > > 
> > > 
> > > When the hell did I do that?
> > 
> > 
> > ask me what you didn't did in terms of stalking girls and making deep fake
> 
> What kind of question is that? You're the one who sent porn in that group chat.

that's was my voice note not the P0rn BRUH

**Comment by ayu2606** [comment]
Also it is boys only gc

**Comment by CR072** [comment]
> > > > > well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere
> > > > 
> > > > 
> > > > When the hell did I do that?
> > > 
> > > 
> > > ask me what you didn't did in terms of stalking girls and making deep fake
> > 
> > 
> > What kind of question is that? You're the one who sent porn in that group chat.
> 
> that's was my voice note not the P0rn BRUH

Well if you insist in lying, then I must personally come to Allahabad and tell you what exactly you've done.

**Comment by CR072** [comment]
> Also it is boys only gc

Never was, it had 2 females in the past and 1 currently.

**Comment by ayu2606** [comment]
> > > > > > well you are the one who commit frauds, you stalk and share girls deepfake pics everywhere
> > > > > 
> > > > > 
> > > > > When the hell did I do that?
> > > > 
> > > > 
> > > > ask me what you didn't did in terms of stalking girls and making deep fake
> > > 
> > > 
> > > What kind of question is that? You're the one who sent porn in that group chat.
> > 
> > 
> > that's was my voice note not the P0rn BRUH
> 
> Well if you insist in lying, then I must personally come to Allahabad and tell you what exactly you've done.

well see discord you monkey

**Comment by ayu2606** [comment]
> > Also it is boys only gc
> 
> Never was, it had 2 females in the past and 1 currently.

oh, then why did u sent ur d pic in that gc?

**Comment by CR072** [comment]
> > > Also it is boys only gc
> > 
> > 
> > Never was, it had 2 females in the past and 1 currently.
> 
> oh, then why did u sent ur d pic in that gc?

I never took a picture of that?

**Comment by ayu2606** [comment]
> > > > Also it is boys only gc
> > > 
> > > 
> > > Never was, it had 2 females in the past and 1 currently.
> > 
> > 
> > oh, then why did u sent ur d pic in that gc?
> 
> I never took a picture of that?

you did, everyone clap for u coz u are competing drake

**Comment by CR072** [comment]
> > > > > Also it is boys only gc
> > > > 
> > > > 
> > > > Never was, it had 2 females in the past and 1 currently.
> > > 
> > > 
> > > oh, then why did u sent ur d pic in that gc?
> > 
> > 
> > I never took a picture of that?
> 
> you did, everyone clap for u coz u are competing drake

What about the women you slept with?

**Comment by ayu2606** [comment]
> > > > > > Also it is boys only gc
> > > > > 
> > > > > 
> > > > > Never was, it had 2 females in the past and 1 currently.
> > > > 
> > > > 
> > > > oh, then why did u sent ur d pic in that gc?
> > > 
> > > 
> > > I never took a picture of that?
> > 
> > 
> > you did, everyone clap for u coz u are competing drake
> 
> What about the women you slept with?

well, I didn't, I lied, I am virgin, I lied because u all think being virgin at this age is crime

**Comment by CR072** [comment]
If you really wanna talk about what we did, why don't we confess it in front of Mr Abhishek Srivastava? I heard he's a good father and a HC registrar.

**Comment by ayu2606** [comment]
> If you really wanna talk about what we did, why don't we confess it in front of Mr Abhishek Srivastava? I heard he's a good father and a HC registrar.

@garimagupta2009 by this we can conclude that @CR072 is a true stalker

**Comment by CR072** [comment]
> > If you really wanna talk about what we did, why don't we confess it in front of Mr Abhishek Srivastava? I heard he's a good father and a HC registrar.
> 
> @garimagupta2009 by this we can conclude that @CR072 is a true stalker

Yes, I am a stalked, I never denied it, but I also mentioned earlier that I only stalk criminals.

**Comment by ayu2606** [comment]
image

**Comment by CR072** [comment]
That's literally edited with inspect element.

**Comment by ayu2606** [comment]
i gotta have dinner now @CR072 see yaa

**Comment by ayu2606** [comment]
> That's literally edited with inspect element.

khao maa kasam

**Comment by CR072** [comment]
> > That's literally edited with inspect element.
> 
> khao maa kasam

image
Well, scroll a bit down lil bro

**Comment by ayu2606** [comment]
> > > That's literally edited with inspect element.
> > 
> > 
> > khao maa kasam
> 
> image Well, scroll a bit down lil bro

oh didnt knew that

**Pull request closed without merging**
